// frontend-frameworks/svelte/src/lib/Calendar.svelte
<script>
    let { data, lifeExpectancy } = $props();

    const yearsArr = $derived([...Array(lifeExpectancy).keys()]);
    const weeksArr = [...Array(52).keys()];
    const weekNum = $derived(lifeExpectancy * 52 - parseInt(data["weeks"]));
    const finalWeek = $derived(lifeExpectancy * 52);

</script>

<section id="calendar">
    <p><i>Each square of dots reqresents 52 weeks / 1 year of your life.</i></p>

    <div class=dozen-grid>
        {#each yearsArr as year, yearIndex}
        <div class="year-grid">
            {#each weeksArr.map((val, valIndex) => {
                const currWeek = yearIndex * 52 + valIndex;
                const dotStyle = currWeek == finalWeek - 1 ? " death" :
                    currWeek < weekNum ? "  solid" : currWeek == weekNum ? "  pulse" : "";
                return {week: val, currWeek, dotStyle};
            }) as week, weekIndex}
            <div class="dot {week.dotStyle}"></div>
            {/each}
        </div>
        {/each}
    </div>
</section>

// frontend-frameworks/vue/src/components/Calendar.vue
<script setup>
import { computed } from 'vue';
const { data, lifeExpectancy } = defineProps({
    lifeExpectancy: Object,
    data: Object
})

const yearsArr = computed(() => [...Array(lifeExpectancy.value).keys()]);
const weeksArr = [...Array(52).keys()];
const weekNum = computed(() => lifeExpectancy.value * 52 - parseInt(data.value["weeks"]));
const finalWeek = computed(() => lifeExpectancy.value * 52);

function getWeeksArr(wksArr, yrIndex) {
    return wksArr.map((val, valIndex) => {
        const currentWeek = yrIndex * 52 + valIndex + 1;
        const dotStyle = currentWeek == finalWeek.value
            ? " death"
            : currentWeek < weekNum.value
                ? "  solid"
                : currentWeek == weekNum.value
                    ? " pulse"
                    : ""
        return { week: val, currentWeek, dotStyle };
    })
}

</script>

<template>
    <section id="calendar">
        <p><i>Each square of dots reqresents 52 weeks / 1 year of your life.</i></p>
        <div class=dozen-grid>
            <div class="year-grid" v-for="(year, yearIndex) in yearsArr" :key="yearIndex">
                <div class="dot" v-for="(week, weekIndex) in getWeeksArr(weeksArr, yearIndex)" :key="weekIndex" :class="week.dotStyle">
                </div>
            </div>
        </div>
    </section>
</template>

<style scoped></style>
