// frontend-frameworks/svelte/src/lib/Portal.svelte
<script>
  const { form, handleCloseModal } = $props();
</script>

<div class="portal-container">
  <div
    role="button"
    tabindex="0"
    onkeydown={() => {}}
    class="portal-underlay"
    onclick={handleCloseModal}
  ></div>
  <div class="portal-content">
    {@render form()}
  </div>
</div>

// frontend-frameworks/vue/src/components/Portal.vue
<script setup>
defineProps({
    showModal: Boolean,
    handleCloseModal: Function
})

</script>

<template>
    <Teleport v-if="showModal" to="#portal">
        <div class="portal-container">
            <div class="portal-underlay" role="button" tabindex="0" @click="handleCloseModal"></div>
            <div class="portal-content">
                <slot />
            </div>
        </div>
    </Teleport>
</template>

<style scoped></style>
